apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: jx-boot
    jenkins-x.io/kind: jx-git-operator
spec:
  backoffLimit: 4
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: jx-boot
        jenkins-x.io/kind: jx-git-operator
    spec:
      initContainers:
      - args:
        - '-c'
        - 'mkdir -p $HOME; git config --global --add user.name $GIT_AUTHOR_NAME; git
          config --global --add user.email $GIT_AUTHOR_EMAIL; git config --global
          credential.helper store; git clone https://${GIT_USER}:${GIT_TOKEN}@${GIT_URL#"https://"}
          ${GIT_SUB_DIR}; echo cloned url: $(inputs.params.url) to dir: ${GIT_SUB_DIR};
          cd ${GIT_SUB_DIR}; git checkout ${GIT_REVISION}; echo checked out revision:
          ${GIT_REVISION} to dir: ${GIT_SUB_DIR}'
        command:
        - /bin/sh
        env:
        - name: GIT_URL
          valueFrom:
            secretKeyRef:
              key: url
              name: jx-boot
        - name: GIT_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: jx-boot
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              key: password
              name: jx-boot
        - name: GIT_REVISION
          value: master
        - name: GIT_SUB_DIR
          value: source
        - name: GIT_AUTHOR_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_NAME
          value: jenkins-x-labs-bot
        - name: GIT_COMMITTER_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_COMMITTER_NAME
          value: jenkins-x-labs-bot
        - name: XDG_CONFIG_HOME
          value: /workspace/xdg_config
        image: gcr.io/jenkinsxio/jx-boot:3.0.731
        name: git-clone
        volumeMounts:
        - mountPath: /workspace
          name: workspace-volume
        workingDir: /workspace
      containers:
      - args:
        - apply
        command:
        - make
        env:
        - name: JX_SECRET_SIDECAR
          value: gsm
        - name: JX_SECRET_TMP_DIR
          value: /workspace/source/.jx-secrets
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: gcr.io/jenkinsxio/jx-boot:3.0.731
        imagePullPolicy: Always
        name: job
        volumeMounts:
        - mountPath: /workspace
          name: workspace-volume
        workingDir: /workspace/source
      - command:
        - versionStream/src/wait-for-complete.sh
        image: google/cloud-sdk:slim
        imagePullPolicy: Always
        name: gsm
        volumeMounts:
        - mountPath: /workspace
          name: workspace-volume
        workingDir: /workspace/source
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      serviceAccountName: jx-boot-job
      terminationGracePeriodSeconds: 30
      volumes:
      - name: workspace-volume
        emptyDir: {}
